version: '3'

services:
  db:
    image: busybox
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      
  app:
    build: .
    command: python app_knad/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  mysqldata:
