# Dockerfile для запуска контейнера MySQL
FROM mysql:8.0.26
FROM pysqlite3

# Задаем кодировку
ENV LANG C.UTF-8

# Копируем файл со схемой базы данных
COPY project/db.sqlite3 /db/

# Устанавливаем права доступ на файл
RUN chmod 644 /db/db.sqlite3

# Окружение по умолчанию
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_ROOT_PASSWORD=mypassword

# Включаем логирование MySQL в /var/log/mysql/mysql.log
RUN touch /var/log/sqlite3.log && chmod 777 /var/log/sqlite3.log && ln -sf /dev/stdout /var/log/sqlite3.log

# Открываем порт 3306  mysqlclient>=1.4.6
EXPOSE 3306

